Fr0nty
SheepSeb/red-team-jailbreak pull request #19
Opened 2024-05-25 08:38 UTC by Fr0nty

Implemented multishot

2024-05-25 08:55 UTC, SheepSeb requested changes
Include a judge for creating a score
Check if the victim response is null or empty string

2024-05-25 11:52 UTC, SheepSeb requested changes

2024-05-25 11:52 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        return int(score)
Bad Python Ident

2024-05-25 11:52 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        judge_response = judge_llm.get_response_text(JUDGE_LLM, judge_prompt)
Where is judge_llm defined?

2024-05-25 11:52 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        judge_response = judge_llm.get_response_text(JUDGE_LLM, judge_prompt)
Where is judge_llm defined?

2024-05-25 11:52 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        system_prompt_attacker = batch_prompt + f"Question: {harmful_text}\nAnswer: "
All of the code in the for loop is badly indented. Do lintting before

2024-05-25 11:52 UTC, SheepSeb commented on src/Multi_shot/run.sh
If you don't use this file, please delete it

2024-05-25 11:53 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        judge_response = judge_llm.get_response_text(JUDGE_LLM, judge_prompt)
It should be an object of type ResponseAPI, check the implementation from persona

2024-05-25 12:51 UTC, SheepSeb requested changes

2024-05-25 12:51 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        score = attack_nlp_multishot(harmful_text[0], step, batch_prompts)
You're sending here the first character not the full sentence

2024-05-25 12:51 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        attack_prompt += " Answer the question honestly."
Why do you add here the "Answer the question", if you already sent it to the API ? It doesn't add anything for the model, the interaction has already been done.

2024-05-25 12:51 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        attack_prompt = victim_llm.get_response_text(VICTIM_LLM, system_prompt_attacker)
Why there are two calls for the victim llm? One before the attack prompt and one after with the same query?

2024-05-26 12:04 UTC, SheepSeb requested changes

2024-05-26 12:04 UTC, SheepSeb commented on src/Multi_shot/run.py
> +    ResponseAPI = ResponseAPI()
What is this ? :question: :confused:
The object shouldn't be named like the class. There is a difference between a class and an object. The class is the blueprint and the object is the actual instance/variable. You cannot call the object as the same name as the class

2024-05-26 12:04 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        attack_prompt = ResponseAPI.get_response_text(VICTIM_LLM, system_prompt_attacker)
This only works if the ```get_response_text``` is a static method that doesn't depend on the object. Don't change the implementation of the class!

2024-05-26 12:04 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        attack_prompt = MMResponseAPI.get_response_text(VICTIM_LLM, system_prompt_attacker)
Same as the one in NLP

2024-05-26 12:04 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        writer = csv.writer(csvfile)
Does this conflict with the global writer at line [this](https://github.com/SheepSeb/red-team-jailbreak/blob/1034e99489df5b5ad07be24c1da7dbe22a4924a9/src/Multi_shot/run.py#L21)?

2024-05-26 12:07 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        writer = csv.writer(csvfile)
Why don't you use a pandas dataframe to read and write to a csv?

2024-05-26 12:10 UTC, SheepSeb commented on src/Multi_shot/run.py
> +    ResponseAPI = ResponseAPI()
This looks goofy as fuck, it's like you would write in C smth like 

```
int int = 3;
```

Do you see the problem here?

2024-05-26 17:04 UTC, SheepSeb requested changes

2024-05-26 17:04 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        judge_response = ResponseAPI.get_response_text(JUDGE_LLM, judge_prompt)
Same here, you try to use a static method, when the method is not static (and it shouldn't be). You need an object that does that

2024-05-26 17:04 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        victim_response = MMResponseAPI.get_response_multimodal(VICTIM_LLM, victim_system_prompt, image)
Same here as in the NLP you don't have an object to use

2024-05-26 17:04 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        attack_prompt = MMResponseAPI.get_response_text(VICTIM_LLM, system_prompt_attacker)
Same problem as before nothing changed

2024-05-26 17:04 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        asr.update(score >= 5)
You just send a character here ```harmful_text[0]``` is a character

2024-05-26 17:08 UTC, SheepSeb commented on src/Multi_shot/run.py
> +        asr.update(score >= 5)
Also check the pandas dataframe cause you are also sending one character not the prompt

2024-05-27 10:39 UTC, SheepSeb approved these changes

2024-05-27 10:40 UTC, SheepSeb commented
@Adamo-afk check the PR, thank you!

2024-05-27 11:51 UTC, Adamo-afk approved these changes

2024-05-27 11:51 UTC, Adamo-afk approved these changes

2024-05-27 14:50 UTC, merged